tags:
- name: Mascotas
  description: Endpoints de Mascotas
- name: Dueños
  description: Endpoints de Dueños
paths:
# [GET] mascotas
  /pet:
    get:
      tags:
      - Mascotas
      summary: Encontrar todas las Mascotas
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] Mascotas
  /pet/{id}:
    post:
      tags:
      - Mascotas
      summary: Agregar nueva Mascota a un Dueño
      parameters:
      - name: id
        in: path
        description: ID del dueño al que se agregará la mascota
        required: true
        type: string
      - name: body
        in: body
        description: Información de la Mascota
        required: true
        schema:
          $ref: '#/definitions/pet'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] pet/id
    get:
      tags:
      - Mascota
      summary: Buscar por el id de la Mascota
      parameters:
      - name: id
        in: path
        description: Id de la Mascota
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] pet/id
    put:
      tags:
      - Mascota
      summary: Actualizar las Mascota por el id
      parameters:
      - name: id
        in: path
        description: Id de la Mascota
        required: true
      - name: body
        in: body
        description: Información de la Mascota
        required: true
        schema:
          $ref: '#/definitions/pet'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] pet/id
    delete:
      tags:
      - Mascota
      summary: Elimina la Mascota por el id
      parameters:
      - name: id
        in: path
        description: Id de la Mascota
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] owner
  /owner:
    get:
      tags:
      - Dueños
      summary: Encontrar todos los Dueños
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] owner
    post:
      tags:
      - Dueños
      summary: Agregar nuevo Dueño
      parameters:
      - name: body
        in: body
        description: Información del Dueño
        required: true
        schema:
          $ref: '#/definitions/owner'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] owner/id
  /owner/{id}:
    get:
      tags:
      - Dueños
      summary: Buscar por el id del Dueño
      parameters:
      - name: id
        in: path
        description: Id del Dueño
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] owner/id
    put:
      tags:
      - Dueños
      summary: Actualizar los Dueños por el id
      parameters:
      - name: id
        in: path
        description: Id del Dueño
        required: true
      - name: body
        in: body
        description: Información del Dueño
        required: true
        schema:
          $ref: '#/definitions/owner'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] owner/id
    delete:
      tags:
      - Dueños
      summary: Elimina el Dueño por el id
      parameters:
      - name: id
        in: path
        description: Id del Dueño
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
  
# definitions
definitions:
  pet:
    type: object
    required:
        - id
        - name
        - race
        - sex
    properties:
      id:
        type: string
        description: Id de la Mascota
        default: 1123
      name:
        type: string
        description: nombre de la Mascota
        default: Canela
      race:
        type: string
        description: Raza de la Mascota
        default: Sabueso
      birthday:
        type: Date
        description: Fecha de Nacimiento de la Mascota
        default: 2021-05-15
      sex:
        type: Boolean
        description: Sexo de la Mascota
        default: true
  owner:
    type: object
    required:
        - id
        - name
        - phone
        - email
    properties:
      id:
        type: string
        description: id del Dueño
        default: 908
      name:
        type: string
        description: Nombre del Dueño
        default: Juanita Sanabria
      phone:
        type: string
        description: Numero del Dueño
        default: 323453421
      email:
        type: string
        description: Correo del Dueño
        default: juanita.sanabria@gmail.com
      pets:
        type: array
        description: Lista de Mascotas de un Dueño 
        items:
          $ref: '#/definitions/pets'
        default: []
schemes:
 - https
 - http